### ISSUE TITLE
Issue with Script 007

### ISSUE THREAD

**Issue by rstevens4086** [mathewhauer/county_projections_official#7]
I am trying to run script 007 and I keep getting the following error message: Error in { : task 1 failed - "object 'Var1' not found". I have searched all over but cannot figure out where Var1 is created for 007 and why this issue is occurring. Any help would be greatly appreciated.

Thank you!

**Comment by mathewhauer** [comment]
I assume this is coming from
`mutate(mutate(AGE = as.numeric(substr(Var1, 2,3)))` on line 398 of `007-projections_2100.R`?

**Comment by rstevens4086** [comment]
Yes

**Comment by mathewhauer** [comment]
Hmm.... I just ran that code and it worked just fine.

![image](https://user-images.githubusercontent.com/16724401/64819492-575ec380-d57c-11e9-898c-9b8dba7bf35b.png)

**Comment by rstevens4086** [comment]
Where is Var1 created? Also is it dependent on any earlier script?

**Comment by mathewhauer** [comment]
Var1 happens as a result of `projm<-projf <- array(0,c(SIZE,1,ncol(lx1f)), dimnames = list(
        c("a1", "a2", "a3", "a4", "a5","a6", "a7", "a8", "a9", "a10", "a11", "a12", "a13", "a14", "a15", "a16", "a17", "a18")))`. a1 through a18 refer to the 18 age groups. Since there is no name, the variable gets a default variable `Var1`.
