### ISSUE TITLE
race2 for geoid 48301

### ISSUE THREAD

**Issue by alpierce21** [mathewhauer/county_projections_official#8]
Hi- I believe the projections dataset is missing race == 2 for geoid == 48301. I found a few other counties missing race2 but those do not have any BLK residents in recent census; geoid 48301 does. Could you send just those missing observations? Thank you!

**Comment by mathewhauer** [comment]
Loving County TX had 0 black residents counted in Census 2010.

**Comment by alpierce21** [comment]
Ok, my mistake. Thank you.
